WITH CTE_BOOK_SALES AS (
    SELECT *
      FROM BOOK_SALES
     WHERE SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
),

CTE_BOOK_AUTHOR AS (
    SELECT B.BOOK_ID, A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE
      FROM BOOK B
INNER JOIN AUTHOR A
        ON B.AUTHOR_ID = A.AUTHOR_ID
)

    SELECT BA.AUTHOR_ID, BA.AUTHOR_NAME, BA.CATEGORY, SUM(BS.SALES * BA.PRICE) AS TOTAL_SALES
      FROM CTE_BOOK_SALES BS
INNER JOIN CTE_BOOK_AUTHOR BA
        ON BS.BOOK_ID = BA.BOOK_ID
  GROUP BY BA.AUTHOR_ID, BA.CATEGORY
  ORDER BY BA.AUTHOR_ID ASC, BA.CATEGORY DESC;