WITH TARGET_PRODUCT AS (
    SELECT * 
      FROM FOOD_ORDER
     WHERE PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
)
 
    SELECT TP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * TP.AMOUNT) AS TOTAL_SALES
      FROM TARGET_PRODUCT TP
INNER JOIN FOOD_PRODUCT FP
        ON FP.PRODUCT_ID = TP.PRODUCT_ID
  GROUP BY TP.PRODUCT_ID
  ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;