# 2세대 추출
WITH ECOLI_2ND AS (
    SELECT E1.ID AS PARENT_ID, E2.ID
      FROM ECOLI_DATA E1
 INNER JOIN ECOLI_DATA E2
        ON E1.ID = E2.PARENT_ID
),
# 3세대 이상 추출
ECOLI_OVER_3RD AS (
    SELECT E1.PARENT_ID, E2.ID
      FROM ECOLI_DATA E1
INNER JOIN ECOLI_2ND E2
        ON E1.ID = E2.PARENT_ID
     WHERE E1.PARENT_ID IS NOT NULL
)
  
# 3세대만 추출
    SELECT E2.ID
      FROM ECOLI_DATA E1
INNER JOIN ECOLI_OVER_3RD E2
        ON E1.ID = E2.PARENT_ID
     WHERE E1.PARENT_ID IS NULL