WITH REVIEW_COUNTS AS (
    SELECT MP.MEMBER_ID, MP.MEMBER_NAME, COUNT(RR.MEMBER_ID) AS `COUNT`
      FROM MEMBER_PROFILE MP
 LEFT JOIN REST_REVIEW RR
        ON MP.MEMBER_ID = RR.MEMBER_ID
  GROUP BY MP.MEMBER_ID
),
MAX_COUNT AS (
    SELECT MAX(`COUNT`) AS MAX_REVIEW_COUNT
      FROM REVIEW_COUNTS
),
BEST_REVIEWERS AS (
    SELECT RC.MEMBER_ID, RC.MEMBER_NAME, RC.`COUNT`
      FROM REVIEW_COUNTS RC, MAX_COUNT MC
     WHERE RC.`COUNT` = MC.MAX_REVIEW_COUNT
)

   SELECT BR.MEMBER_NAME, RR.REVIEW_TEXT, date_format(RR.REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
     FROM BEST_REVIEWERS BR
LEFT JOIN REST_REVIEW RR
       ON BR.MEMBER_ID = RR.MEMBER_ID
 ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;
    
 