    SELECT FH.FLAVOR
      FROM FIRST_HALF as FH
INNER JOIN ICECREAM_INFO as II
        ON FH.FLAVOR = II.FLAVOR 
     WHERE FH.TOTAL_ORDER > 3000
       AND II.INGREDIENT_TYPE = 'fruit_based'
  ORDER BY FH.TOTAL_ORDER DESC;