# SELECT date_format(FULLTABLE.SALES_DATE, "%Y-%m-%d"), FULLTABLE.PRODUCT_ID, IFNULL(FULLTABLE.USER_ID, "NULL") as USER_ID, FULLTABLE.SALES_AMOUNT
#   FROM (
#                SELECT ONLINE.*
#                  FROM ONLINE_SALE ONLINE
#             LEFT JOIN OFFLINE_SALE OFFLINE
#                    ON ONLINE.PRODUCT_ID = OFFLINE.PRODUCT_ID
#                 UNION
#                SELECT ONLINE.*
#                  FROM ONLINE_SALE ONLINE
#            RIGHT JOIN OFFLINE_SALE OFFLINE
#                    ON ONLINE.PRODUCT_ID = OFFLINE.PRODUCT_ID
#   ) as FULLTABLE
#  WHERE FULLTABLE.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31';


SELECT date_format(SALES_DATE, "%Y-%m-%d"), 
       PRODUCT_ID, 
       USER_ID, 
       SALES_AMOUNT
FROM (
    -- ONLINE_SALE 테이블에서 데이터를 선택
    SELECT SALES_DATE, 
           PRODUCT_ID, 
           USER_ID, 
           SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

    UNION

    -- OFFLINE_SALE 테이블에서 데이터를 선택 (USER_ID는 NULL)
    SELECT SALES_DATE, 
           PRODUCT_ID, 
           NULL AS USER_ID,  -- USER_ID는 NULL로 설정
           SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
) AS COMBINED_SALES
-- 정렬 조건: 판매일 오름차순, 상품 ID 오름차순, 유저 ID 오름차순
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;