/* 
초기 with 절 이렇게 하면 안된다.
이렇게 하면 여러개의 이력이 존재하는 상황에서 조건에 맞는것만 뽑아오고 만일 11월에 대여기록이 있어도 해당 테이블에 포함되게 되므로 오류
*/
# WITH AVAILABLE_CAR AS (
 #    SELECT CR2.CAR_ID, CR2.CAR_TYPE, CR2.DAILY_FEE
 #      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR1
 # LEFT JOIN CAR_RENTAL_COMPANY_CAR CR2
 #        ON CR1.CAR_ID = CR2.CAR_ID
#      WHERE (START_DATE < "2022-11-01" AND END_DATE < "2022-11-01")
#         OR (START_DATE > "2022-11-30" AND END_DATE > "2022-11-30")
#   ORDER BY CAR_ID
# ),

# 추가) 단순히 대여날짜와 반납날짜가 11월에 포함된것만 고르면 안됨.
# 10월에 빌려서 12월에 빌린것과 같은 장기 대여도 생각했어야함.

WITH AVAILABLE_CAR AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE 
      FROM CAR_RENTAL_COMPANY_CAR
     WHERE CAR_ID NOT IN(
                SELECT CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE BETWEEN "2022-11-01" AND "2022-11-30"
                    OR END_DATE BETWEEN "2022-11-01" AND "2022-11-30"
                    OR (START_DATE < "2022-11-01" AND END_DATE > "2022-11-30")
    ) 
    AND (CAR_TYPE = "SUV" OR CAR_TYPE = "세단")
),
DISCOUNT_RATE_OVER_30 AS (
    SELECT * 
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE = "30일 이상"
)

   SELECT  AC.CAR_ID, 
   AC.CAR_TYPE, 
   ROUND(((100 - DR.DISCOUNT_RATE) / 100) * AC.DAILY_FEE * 30) AS FEE
      FROM AVAILABLE_CAR AC
 LEFT JOIN DISCOUNT_RATE_OVER_30 DR
        ON AC.CAR_TYPE = DR.CAR_TYPE
    HAVING FEE >= 500000 AND FEE < 2000000
  ORDER BY FEE DESC, AC.CAR_TYPE ASC, AC.CAR_ID DESC;