WITH REST_CTE AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
      FROM REST_INFO
)

  SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
    FROM REST_CTE
   WHERE RN = 1
ORDER BY FOOD_TYPE DESC;