SELECT 
        RANK_TABLE.ID,
        CASE 
            WHEN RANK_TABLE.RANK_OF_SIZE <= 0.25 * COUNT(*) THEN "CRITICAL"
            WHEN RANK_TABLE.RANK_OF_SIZE <= 0.5 * COUNT(*) THEN "HIGH"
            WHEN RANK_TABLE.RANK_OF_SIZE <= 0.75 * COUNT(*) THEN "MEDIUM"
            ELSE "LOW"
        END AS COLONY_NAME
FROM ECOLI_DATA E, 
      (
          SELECT ID, SIZE_OF_COLONY, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_OF_SIZE
            FROM ECOLI_DATA
      ) RANK_TABLE
    GROUP BY RANK_TABLE.RANK_OF_SIZE, RANK_TABLE.ID
    ORDER BY RANK_TABLE.ID ASC