# 한 USER가 같은 달에 여러번 구매한 내역이 있을 수 있기 때문에 COUNT 시 DISTINCT를 통해 중복을 제거
   SELECT YEAR(O.SALES_DATE) AS `YEAR`, MONTH(O.SALES_DATE) AS `MONTH`, U.GENDER, 
            COUNT(DISTINCT O.USER_ID) AS `USERS`
     FROM ONLINE_SALE O
LEFT JOIN USER_INFO U
       ON U.USER_ID = O.USER_ID
    WHERE GENDER IS NOT NULL
 GROUP BY `YEAR`, `MONTH`, `GENDER`
   HAVING GENDER IS NOT NULL
 ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;