# 데이터가 없는 경우에 대한 쿼리문을 작성하는 방법을 요구하고 있음.

WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL 
    SELECT HOUR + 1
      FROM HOURS
     WHERE HOUR < 23
)

   SELECT H.HOUR, IFNULL(COUNT(A.ANIMAL_ID),0) AS `COUNT`
     FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
       ON HOUR(A.DATETIME) = H.HOUR
 GROUP BY HOUR
 ORDER BY HOUR ASC;