WITH CTE_GRADE AS (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
      FROM HR_GRADE
     WHERE YEAR = 2022
  GROUP BY EMP_NO
)

  SELECT HE.EMP_NO, HE.EMP_NAME, 
        CASE
            WHEN CG.SCORE >= 96 THEN "S"
            WHEN CG.SCORE >= 90 THEN "A"
            WHEN CG.SCORE >= 80 THEN "B"
            ELSE "C"
        END AS GRADE, 
        CASE
            WHEN CG.SCORE >= 96 THEN HE.SAL * 0.2
            WHEN CG.SCORE >= 90 THEN HE.SAL * 0.15
            WHEN CG.SCORE >= 80 THEN HE.SAL * 0.1
            ELSE 0
        END AS BONUS 
      FROM HR_EMPLOYEES HE
 LEFT JOIN CTE_GRADE CG
        ON HE.EMP_NO = CG.EMP_NO
  ORDER BY HE.EMP_NO ASC;

