# SELECT ID, GENOTYPE, PARENT_GENOTYPE
# 부모의 형질 & 자식의 형질 = 부모의 형질인 녀석들만 SELECT
# 그래야 부모의 형질이 자식의 형질에 모두 포함된 녀석들만 골라올 수 있음.

   SELECT E2.ID, E2.GENOTYPE, E1.GENOTYPE AS PARENT_GENOTYPE
     FROM ECOLI_DATA E1
LEFT JOIN ECOLI_DATA E2
       ON E1.ID = E2.PARENT_ID
      AND E1.GENOTYPE & E2.GENOTYPE = E1.GENOTYPE
    WHERE E2.ID IS NOT NULL
 ORDER BY E2.ID ASC;