  # IFNULL(), CASE, COALESCE
  # https://velog.io/@gillog/DB-MySQL-NULL-%EC%B2%98%EB%A6%ACIFNULL-CASE-COALESCE
  
  SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') as 'TLNO'
    FROM PATIENT
   WHERE GEND_CD = 'W'
     AND AGE <= 12
ORDER BY AGE DESC, PT_NAME ASC;
  