/*
    YEAR() : 년만 추출
    MONTH() : 월만 추출
    DAY() : 일만 추출
    */
WITH CTE_CAR_RENTAL AS (
    SELECT CAR_ID, COUNT(*) AS COUNT
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
  GROUP BY CAR_ID
    HAVING COUNT >= 5
)

    SELECT MONTH(C2.START_DATE) AS MONTH, C2.CAR_ID, COUNT(*) AS RECORDS
      FROM CTE_CAR_RENTAL C1
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
        ON C1.CAR_ID = C2.CAR_ID
     WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
  GROUP BY MONTH(C2.START_DATE), CAR_ID
    HAVING RECORDS != 0
  ORDER BY MONTH ASC, CAR_ID DESC;