SELECT COUNT(*) as FISH_COUNT
  FROM (
    SELECT *
      FROM FISH_NAME_INFO
     WHERE FISH_NAME = 'BASS'
        OR FISH_NAME = 'SNAPPER'
  ) TARGET_FISH, FISH_INFO
 WHERE FISH_INFO.FISH_TYPE = TARGET_FISH.FISH_TYPE