WITH CTE_GRADE AS (
    SELECT EMP_NO, YEAR, SUM(SCORE) AS SCORE
      FROM HR_GRADE 
     WHERE YEAR = 2022
  GROUP BY EMP_NO
),
COMPANY_INFO AS (
    SELECT he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL, he.DEPT_ID,hd.DEPT_NAME_KR
      FROM HR_EMPLOYEES he
 LEFT JOIN HR_DEPARTMENT hd
        ON he.DEPT_ID = hd.DEPT_ID
)

   SELECT CG.SCORE, CG.EMP_NO, CI.EMP_NAME, CI.POSITION, CI.EMAIL
     FROM CTE_GRADE CG
LEFT JOIN COMPANY_INFO CI
       ON CG.EMP_NO = CI.EMP_NO
 ORDER BY CG.SCORE DESC
    LIMIT 1;