   SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
     FROM ITEM_INFO II
    WHERE II.ITEM_ID NOT IN (
        SELECT II.ITEM_ID
          FROM ITEM_TREE IT
     LEFT JOIN ITEM_INFO II
            ON IT.PARENT_ITEM_ID = II.ITEM_ID
         WHERE II.ITEM_ID IS NOT NULL
      GROUP BY II.ITEM_ID
    )
ORDER BY II.ITEM_ID DESC;
   

