# 검색기반 본인 풀이
WITH MAX_PRICE_CTE AS (
    SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY, 
    ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN
      FROM FOOD_PRODUCT
     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)

   SELECT FP.CATEGORY, FP.PRICE AS 'MAX_PRICE', FP.PRODUCT_NAME
     FROM FOOD_PRODUCT FP
LEFT JOIN MAX_PRICE_CTE MPC
       ON FP.PRODUCT_ID = MPC.PRODUCT_ID 
    WHERE MPC.RN = 1
 ORDER BY MAX_PRICE DESC;
 
 # chat GPT 풀이 다른경우
#  WITH MAX_PRICE_CTE AS (
#     SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
#       FROM FOOD_PRODUCT
#      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
#      GROUP BY CATEGORY
# )
#   SELECT FP.PRODUCT_ID, FP.PRICE AS 'MAX_PRICE', FP.CATEGORY
#     FROM FOOD_PRODUCT FP
#     JOIN MAX_PRICE_CTE MPC
#       ON FP.CATEGORY = MPC.CATEGORY
#      AND FP.PRICE = MPC.MAX_PRICE
# ORDER BY MAX_PRICE DESC;
