WITH FISH_LENGTH AS (
    SELECT FISH_TYPE, 
        CASE
            WHEN LENGTH <= 10 THEN 10
            ELSE LENGTH
        END AS LENGTH
      FROM FISH_INFO
),
AVG_FISH_LENGTH AS (
    SELECT FISH_TYPE, AVG(LENGTH) AS `LENGTH`
      FROM FISH_LENGTH
  GROUP BY FISH_TYPE
    HAVING `LENGTH` >= 33
)

     SELECT COUNT(*) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, AFL.FISH_TYPE 
       FROM AVG_FISH_LENGTH AFL
  LEFT JOIN FISH_INFO FI
         ON AFL.FISH_TYPE = FI.FISH_TYPE
        AND AFL.LENGTH IS NOT NULL
   GROUP BY AFL.FISH_TYPE
   ORDER BY AFL.FISH_TYPE ASC;
        
