# null 조건 잊지 말것. 문제로 똑바로 읽기.

WITH FISH_LENGTH AS (
    SELECT FISH_TYPE, 
        CASE
            WHEN LENGTH <= 10  OR LENGTH IS NULL THEN 10
            ELSE LENGTH
        END AS `LENGTH`
      FROM FISH_INFO
),
AVG_FISH_LENGTH AS (
    SELECT FISH_TYPE, AVG(LENGTH) AS `LENGTH`
      FROM FISH_LENGTH
  GROUP BY FISH_TYPE
    HAVING `LENGTH` >= 33
)

     SELECT COUNT(*) AS FISH_COUNT, MAX(FL.LENGTH) AS MAX_LENGTH, AFL.FISH_TYPE 
       FROM AVG_FISH_LENGTH AFL
  LEFT JOIN FISH_LENGTH FL
         ON AFL.FISH_TYPE = FL.FISH_TYPE
        AND AFL.LENGTH IS NOT NULL
   GROUP BY AFL.FISH_TYPE
   ORDER BY AFL.FISH_TYPE ASC;