WITH JULY_GROUP AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM JULY
  GROUP BY FLAVOR
),
UNION_CTE_TABLE AS (
    SELECT FH.FLAVOR, (FH.TOTAL_ORDER + JG.TOTAL_ORDER) AS TOTAL_ORDER
      FROM FIRST_HALF FH
INNER JOIN JULY_GROUP JG
        ON FH.FLAVOR = JG.FLAVOR
  GROUP BY FH.FLAVOR
  ORDER BY TOTAL_ORDER DESC
)

SELECT FLAVOR
  FROM UNION_CTE_TABLE
 LIMIT 3;
     